<?php
require_once("tops_lib/model/TEntityObject.php");

class TFdsClass extends TEntityObject {

    // -- Generated by tools/newentity.php
    public function  __construct()
    {
        $this->tableName = 'fdsclasses';
        $this->idFieldName = 'id';
        $this->addField('id',INT_FIELD);
        $this->addField('code',STRING_FIELD);
        $this->addField('name',STRING_FIELD);
    }  //  TFdsClass

    function getCode() {
        return $this->get('code');
    }
    function setCode($value) {
        $this->setFieldValue('code',$value);
    }

    function getName() {
        return $this->get('name');
    }
    function setName($value) {
        $this->setFieldValue('name',$value);
    }
    // -- end generated code


    private static function cloneClassItem(FdsClassListItem $item) {
        $result = new FdsClassListItem();
        $result->id = $item->id;
        $result->name = $item->name;
        return $result;
    }

    public static function GetClassList() {
        $result = array();
        $sql = 'SELECT c.id, c.name FROM fdsclasses c';

        $statement = TSqlStatement::ExecuteQuery($sql);

        $item = new FdsClassListItem();

        $statement->instance->bind_result(
            $item->id,
            $item->name);

        while ($statement->next()) {
            array_push($result, self::cloneClassItem($item));
        }
        return $result;
    }

} // end class

