	<div id="yui-main">      <!-- YUI MAIN -->
        <div class="yui-b expandForPrint"> <!-- YUI b -->
            <div class="yui-g leftContent">  <!-- YUI g -->
                <?php include("$includePath/content_main.inc"); ?>
	        </div> <!-- end YUI g -->
        </div>    <!-- end YUI b -->
    </div> <!-- end YUI main -->

	<div id="rightColumn" class="yui-b doNotPrint"> <!-- YUI b -->
         <?php print $right ?>
    </div> <!-- end YUI b -->

