<!-- 2 column   left 180 -->
	<div id="leftColumn" class="yui-b doNotPrint">
         <?php print $left ?>
    </div>
	<div id="yui-main">  <!-- YUI main -->
    	<div id="mainContent" class="yui-b expandForPrint">  <!-- YUI b -->
            <div class="yui-g">
                <?php include("$includePath/content_main.inc"); ?>
        	</div> <!-- end YUI g -->
        </div>    <!-- end YUI b -->
	</div> <!-- END YUI Main -->
